export const api = {
  // MAIN_URL: 'http://demo.highsoft.ir',
  MAIN_URL: 'https://www.highsoft.ir',
  // MAIN_URL: 'https://news.highsoft.ir',
  // MAIN_URL: 'http://10.1.24.180',
  API_LOGIN: '/web/session/authenticate',
  API_SEARCH_PRODUCT: '/api/v1/pos/product/search',
  API_COUNT_STORE_ORDERS: '/api/v1/pos/order/count',
  API_INFORMATION_PRODUCT_BY_NAME: '/api/v1/pos/product/search',
  API_INFORMATION_PROFILE: '/app/newprofile',
  API_CATEGORIES: '/api/v1/pos/category',
  API_UOM_LIST: '/api/v1/pos/uom_list',
  API_UPDATE_PRODUCT: '/api/v1/pos/product/update',
  API_CREATE_PRODUCT: '/api/v1/pos/product/create',
  API_UPDATE_QUANTITY: '/api/v1/product/qty/update',
  API_REPORT_SALE: '/app/report_sum_sale',
  API_INTERNET_ORDERS: '/app/saleorder_read',
  API_SET_TO_DELIVERY_MAN: '/app/express_delivery_one_step',
  API_SET_STATE_CUSTOMER: '/app/customerdelivery',
  API_DETAILS_INTERNET_ORDERS: '/app/saleorder/orderline',
  API_IN_PERSON_ORDER: '/app/pos_order_read',
  API_DETAILS_IN_PERSON_ORDER: '/app/pos_line_read',
  API_SET_AVAILABLE_PRODUCT: '/app/set_available',
  API_SET_NOT_AVAILABLE_PRODUCT: '/app/set_not_available',
  API_SET_SUGGESTED_PRODUCT: '/app/suggested_product',
  API_STATE_EDIT: '/app/editorder',
  URL_PRODUCT_IMAGE: '/web/image/product.template/',
  URL_PRODUCT_PRODUCT_IMAGE: '/web/image/product.product/',
  URL_PRODUCT_IMAGE_SECTION_2: '/image/300x300'
}
