export const valueString = {
  LABEL_LOGIN_BUTTON: 'ورود',
  LABEL_LOGIN_USER_NAME: 'نام کاربری',
  LABEL_LOGIN_PASSWORD: 'کلمه عبور',
  LABEL_LOGIN_REMEMBER_ME: 'مرا به خاطر بسپار',
  LABEL_ITEM_HOME_IMPORT_PRODUCT: 'تعریف کالا',
  LABEL_ITEM_HOME_NEED_SHOP: 'نیاز های فروشگاه',
  LABEL_ITEM_HOME_HELP_SHOP: 'راهنما',
  LABEL_ITEM_HOME_REPORT_SALE_INTERNET: 'سفارشات اینترنتی',
  LABEL_ITEM_HOME_REPORT_SALE_IN_PERSON: 'سفارشات حضوری',
  LABEL_ITEM_MENU_HOME: 'خانه',
  LABEL_ITEM_MENU_ُSUPPORT: 'تماس با پشتیبانی',
  LABEL_SELECT_DELIVERY_MAN: 'انتخاب پیک',
  LABEL_DELIVERY_TO_CUSTOMER: 'تحویل به مشتری',
  LABEL_PREPARATION_ORDER: 'اماده سازی سفارش',
  LABEL_SET_TO_CONFIRM_CUSTOMER: 'ارسال به مشتری برای تایید',
  LABEL_SELECT_PAK: 'تحویل به پیک',
  LABEL_INFORMATION_PAK: 'اطلاعات پیک',
  LABEL_ITEM_MENU_HELP: 'راهنما',
  LABEL_ITEM_MENU_EXIT: 'خروج',
  LABEL_DETAILS_PAGE_CHANGE_IMAGE: 'انتخاب تصویر جدید',
  LABEL_IMPORT_PAGE_TITLE: ': به کمک یکی از روش های زیر محصول را جستجو کنید',
  LABEL_IMPORT_PAGE_BARCODE: 'بارکد خوان',
  LABEL_DETAILS_PAGE_TITLE: 'جزئیات محصول',
  LABEL_DETAILS_PAGE_NAME: ': نام کالا',
  LABEL_DETAILS_PAGE_BARCODE: ': بار کد',
  LABEL_DETAILS_PAGE_PRICE_IN_PERSON: '(' + 'قیمت فروش حضوری(ریال',
  LABEL_DETAILS_PAGE_PRICE_INTERNET: '(' + 'قیمت فروش اینترنتی(ریال',
  LABEL_DETAILS_PAGE_DISCOUNT_INTERNET: 'در صد تخفیف فروش اینترنتی ',
  LABEL_DETAILS_PAGE_DISCOUNT_INTERNET_FIX: 'تخفیف ثابت اینترنتی ',
  LABEL_DETAILS_PAGE_PERCENT_DISCOUNT: '(' + 'تخفیف (درصد',
  LABEL_DETAILS_PAGE_PRICE_DISCOUNT: '(' + 'تخفیف (مبلغ به ریال',
  LABEL_DETAILS_PAGE_PRICE_BUY: '(' + 'قیمت خرید(ریال',
  LABEL_DETAILS_PAGE_CATEGORIES: 'دسته بندی',
  LABEL_DETAILS_PAGE_UOM: 'واحد اندازه گیری',
  LABEL_DETAILS_PAGE_SHOW_IN_SITE: 'نمایش در سایت',
  LABEL_DETAILS_PAGE_UPDATE: 'به روز رسانی',
  LABEL_DETAILS_PAGE_CREATE: 'اضافه کردن ',
  LABEL_DETAILS_PAGE_CANCEL: 'لغو',
  LABEL_DETAILS_PAGE_MESSAGE_NAME: 'نام محصول نمی تواند خالی باشد',
  LABEL_DETAILS_PAGE_MESSAGE_IN_PERSON_PRICE: 'قیمت فروش حضوری نمی تواند خالی باشد',
  LABEL_DETAILS_PAGE_UPDATE_SET_QUANTITY: 'به روز رسانی اطلاعات و موجودی محصول',
  LABEL_DETAILS_PAGE_MESSAGE_NOT_FIND_PRODUCT: 'محصولی با این نام پیدا نشد',
  LABEL_SET_QUANTITY_TITLE: 'به روز رسانی موجودی',
  LABEL_SET_QUANTITY_TITLE_BUTTON: 'به روز رسانی اطلاعات و موجودی محصول',
  LABEL_SET_QUANTITY_MESSAGE_SUCCESS_SET_QUANTITY: 'موجودی محصول با موفقیت به روز رسانی شد',
  LABEL_SET_QUANTITY_MESSAGE_FAIL_SET_QUANTITY: 'مقدار صحیح وارد نمایید',
  LABEL_COMPONENT_SALE_COUNTER_DAILY: ': فروش روز جاری',
  LABEL_COMPONENT_SALE_COUNTER_MONTHLY: ': فروش ماه جاری',
  LABEL_COMPONENT_SALE_COUNTER_REAL: 'ریال',
  LABEL_NEED_STORE_TITLE: 'تعداد فروش در ماه گذشته و پیشنهاد خرید برای آینده را مشاهده نمایید',
  LABEL_NEED_STORE_PLACEHOLDER_BARCODE: 'بار کد محصول مورد نظر خود را وارد نمایید',
  LABEL_INTERNET_SALE_HEADER_NEW: 'سفارشات جدید',
  LABEL_INTERNET_SALE_HEADER_WAITING: 'منتظرتاییدمشتری',
  LABEL_INTERNET_SALE_HEADER_PACK: 'تحویل به پیک',
  LABEL_INTERNET_SALE_HEADER_DELIVERY: 'تحویل به مشتری',
  LABEL_INTERNET_SALE_HEADER_LIST_NUMBER: 'شماره',
  LABEL_INTERNET_SALE_HEADER_LIST_CUSTOMER: 'مشتری',
  LABEL_INTERNET_SALE_HEADER_LIST_DATE: 'تاریخ',
  LABEL_INTERNET_SALE_HEADER_LIST_MONEY: 'مبلغ',
  LABEL_IN_PERSON_SALE_HEADER_LIST_CODE: 'کد رسید',
  LABEL_IN_PERSON_SALE_HEADER_LIST_SELLER: 'فروشنده',
  LABEL_INTERNET_SALE_MESSAGE_NOT_ORDER: 'هیچ سفارشی ثبت نشده است',
  LABEL_DETAILS_PAGE_MESSAGE_NOT_NAME: ' نام و یا بار کد محصول را وارد نمایید',
  LABEL_DETAILS_PAGE_MESSAGE_NOT_BARCODE: ' بار کد محصول را وارد نمایید',
  LABEL_DETAILS_PAGE_MESSAGE_NOT_USERNAME: 'نام کاربری یا کلمه عبور اشتباه است',
  LABEL_DETAILS_PAGE_MESSAGE_SUCCESS_UPDATE: 'اطلاعات محصول با موفقیت به روز رسانی شد',
  LABEL_DETAILS_PAGE_MESSAGE_SUCCESS_CREATE: 'اطلاعات محصول جدید با موفقیت اضافه شد ',
  LABEL_DETAILS_PAGE_MESSAGE_FAIL_SELECT_DELIVERY_MAN: 'پیک را انتخاب نمایید',
  LABEL_DETAILS_PAGE_MESSAGE_FAIL_EMPTY_SUGGEST_PRODUCT: 'بارکد محصول پیشنهادی خود را وارد نمایید',
  LABEL_DETAILS_PAGE_MESSAGE_FAIL_CREATE: 'اطلاعات محصول جدید با موفقیت اضافه نشد ',
  LABEL_DETAILS_PAGE_MESSAGE_FAIL_UPDATE: 'اطلاعات محصول با موفقیت به روز رسانی نشد',
  LABEL_DETAILS_PAGE_NEED_TITLE: 'جزئیات نیاز های فروشگاه',
  LABEL_DETAIL_PAGE_NEED_CONTENT_TITLE: 'جزئیات نیاز فروشگاه شما',
  LABEL_DETAILS_PAGE_NEED_TO_DAY: ': نیاز های امروز',
  LABEL_DETAILS_PAGE_NEED_TO_WEEK: ': نیاز های هفته',
  LABEL_DETAILS_PAGE_NEED_TO_MONTH: ': نیاز های ماه آینده',
  LABEL_DETAILS_PAGE_NEED_LAST_MONTH: ': نیاز های ماه گذشته',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_TITLE: 'جزئیات فروش اینترنتی',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_TITLE_INFO: 'جزئیات سفارش',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_TITLE_LIST: 'لیست سفارش کالا',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_TITLE_MONEY: 'اطلاعات مالی',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_DATE: ': تاریخ و ساعت',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_ORDER_NUMBER: ': شماره سفارش',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_ORDER_MONEY: ' مبلغ  : ',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_CUSTOMER: 'مشتری : ',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_ORDER_ADDRESS: ': آدرس',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_ORDER_NOTES: ': یادداشت مشتری',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_DISCOUNT_SHOP: ' تخفیفات فروشگاه :',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_MONEY_CUSTOMER: 'مبلغ دریافتی از مشتری :',
  LABEL_DETAILS_TOTAL_PRICE: 'مبلغ کل سفارش :',
  LABEL_DETAILS_USE_CREDIT: ': مقدار استفاده از اعتبار',
  LABEL_DETAILS_PAGE_INTERNET_ORDER_BUTTON_SHOW_LINES: 'مشاهده لیست اقلام سفارش',
  LABEL_DETAILS_PAGE_IN_PERSON_ORDER_TITLE: 'جزئیات فروش حضوری',
  LABEL_MESSAGE_DELIVERY_ORDER: ' سفارش به مشتری تحویل داده شده است ',
  LABEL_DETAILS_PAGE_IN_PERSON_ORDER_CODE: 'کد سفارش : ',
  LABEL_DETAILS_PAGE_IN_PERSON_ORDER_DATE: ' تاریخ و ساعت سفارش : ',
  LABEL_DETAILS_PAGE_IN_PERSON_SELLER: 'نام فروشنده :',
  LABEL_DETAILS_PAGE_IN_PERSON_CUSTOMER: ' نام مشتری :',
  LABEL_BUTTON_CONFIRM: 'تایید',
  LABEL_BARCODE_READER_PAGE_TITLE: 'بارکد خوان',
  LABEL_MESSAGE_EXIT: 'آیا برای خروج از برنامه اطمینان دارید؟',
  LABEL_MESSAGE_YES: 'بله',
  LABEL_MESSAGE_NO: 'خیر',
  LABEL_MONEY_UNIT: 'تومان',
  LABEL_NOT_INTERNET: 'اتصال شما با اینترنت قطع شده است',
  LABEL_MESSAGE_NOT_PRODUCT: 'محصولی با این بار کد ثبت نشده است',
  LABEL_DELIVERY_CODE: 'کد تحویل',
  LABEL_ENTER_NEW_PRODUCT: 'بار کد محصول پیشنهادی خود را وارد نمایید',
  LABEL_ENTER_ADD_NEW_PRODUCT_BUTTON: 'افرودن محصول پیشنهادی',
  LABEL_TITLE_MESSAGE: 'بارکد محصول را وارد نمایید',
  LABEL_BUTTON:"شروع برنامه"
}
